### ISSUE TITLE
manual install (windows)

### ISSUE THREAD

**Issue by My1** [DomBlack/php-scrypt#43]
just a question:
pecl is annoying the hell out of me, the latest errors being

WARNING: php_bin C:\xampp\php\.\php.exe appears to have a suffix .exe, but config variable php_suffix does not match
ERROR: The DSP scrypt.dsp does not exist.

is there a way to install it without all those obnoxious gimmick software?
-> this is the exact reason why I refuse to use extra software like composer and similar for such small stuff...
I saw a DLL lying on the pecl servers, can I just download that and include it as extension?

**Comment by DomBlack** [comment]
Yes the DLL on the pecl servers should be ok if you grab the right one for your PHP install (TS vs non TS).
