### ISSUE TITLE
Show salt in hex instead of binary

### ISSUE THREAD

**Issue by Serphentas** [DomBlack/php-scrypt#50]
Hi,

I've encountered some issues with the salt being displayed in binary form. To be uniform with other hash functions, I think it would be better to use a hex output.

**Comment by DomBlack** [comment]
I'm a little confused, do you mean the example  `generateSalt` function or the underlying `scrypt` function itself?

Both by default return the output in hex, with the `scrypt` function returning raw binary if you set the last parameter to `true`: 

```php
echo scrypt('testing123', '123', 16384, 8, 1, 32);
// Prints 'ecb460b0448475d3a29ef26fe655fc3a09e6285e4a52f2ecb61bdab075fa1370';
echo scrypt('testing123', '123', 16384, 8, 1, 32, true);
// Prints '�`�D�uӢ��o�U�:	�(^JR���u�p';
```

And the last line of the `generateHash` funciton being:

```php
$salt = str_replace(array('+', '$'), array('.', ''), base64_encode($buffer));
```

**Comment by Serphentas** [comment]
I was referring to the output of the hash function, when it prints the parameters, the salt and the actual hash. For example:
`16$8$1$salt$hash`

However the issued I has was related to me using an older version of your wrapper. The new one correctly shows the salt in hex form.

Sorry about the confusion.

**Comment by DomBlack** [comment]
No problem.
